apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: nginx-helm
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
    targetRevision: 2.13.3
    chart: sealed-secrets
  sources: []
  project: default
