apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ignore-differences
  namespace: openshift-gitops
spec:
  destination:
    namespace: nginx-ignore-differences
    server: 'https://kubernetes.default.svc'
  source:
    path: app/ignore-differences
    repoURL: 'https://github.com/xkoww/argocd-example.git'
    targetRevision: HEAD
  sources: []
  project: default
  # ignoreDifferences:
  # - group: "apps"
  #   kind: "Deployment"
  #   jsonPointers:
  #   - /spec/replicas
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      # - RespectIgnoreDifferences=true

