apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: source
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: nginx-source
    server: 'https://kubernetes.default.svc'
  source:
    path: app/source
    repoURL: 'https://github.com/xkoww/argocd-example.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true