apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: target
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: nginx-target
    server: 'https://kubernetes.default.svc'
  source:
    path: app/target
    repoURL: 'https://github.com/xkoww/argocd-example.git'
    targetRevision: HEAD
    directory:
      recurse: false
  sources: []
  project: default
