apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello-world
  labels:
    app: nginx-hello-world
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"nginx-hello-world","app.kubernetes.io/instance":"prune"},"name":"nginx-hello-world","namespace":"nginx-prune"},"spec":{"ports":[{"name":"nginx","port":80,"protocol":"TCP","targetPort":8080}],"selector":{"app":"nginx-hello-world"},"sessionAffinity":"None","type":"ClusterIP"}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-hello-world
  template:
    metadata:
      labels:
        app: nginx-hello-world
    spec:
      containers:
        - name: nginx
          image: "harbor.cnsdomain.com/argocd/nginx:v0.0.1"
          ports:
            - containerPort: 8080