apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: source-fail
  namespace: openshift-gitops
spec:
  destination:
    namespace: nginx-source-fail
    server: 'https://kubernetes.default.svc'
  source:
    path: guestbook
    repoURL: 'https://github.com/argoproj/argocd-example-apps.git'
    targetRevision: HEAD
  sources: []
  project: source
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
