apiVersion: apps/v1
kind: Deployment
metadata:
  name: postsync
  labels:
    app: postsync
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postsync
  template:
    metadata:
      labels:
        app: postsync
    spec:
      containers:
        - name: nginx
          image: "harbor.cnsdomain.com/argocd/nginx:v0.0.1"
          ports:
            - containerPort: 8080
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh","-c","sleep 5"]