apiVersion: apps/v1
kind: Deployment
metadata:
  name: wave
  labels:
    app: wave
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wave
  template:
    metadata:
      labels:
        app: wave
    spec:
      containers:
        - name: nginx
          image: "harbor.cnsdomain.com/argocd/nginx:v0.0.1"
          ports:
            - containerPort: 8080
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh","-c","sleep 5"]