apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello-world
  labels:
    app: nginx-hello-world
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"nginx-hello-world","app.kubernetes.io/instance":"branch"},"name":"nginx-hello-world","namespace":"nginx-branch"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"nginx-hello-world"}},"template":{"metadata":{"labels":{"app":"nginx-hello-world"}},"spec":{"containers":[{"image":"harbor.cnsdomain.com/argocd/nginx:v0.0.1","name":"nginx","ports":[{"containerPort":8080}]}]}}}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-hello-world
  template:
    metadata:
      labels:
        app: nginx-hello-world
    spec:
      containers:
        - name: nginx
          image: "harbor.cnsdomain.com/argocd/nginx:v0.0.1"
          ports:
            - containerPort: 8080