apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{name}}-nginx"
    spec:
      project: default
      source:
        repoURL: "https://github.com/xkoww/argocd-example.git"
        targetRevision: HEAD
        path: app/source
      destination:
        namespace: "cluster"
        server: "{{server}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
